FROM ruby:3.3.10

WORKDIR /app

RUN apt-get update -qq && \
    apt-get install -y \
      build-essential \
      nodejs \
      postgresql-client \
      libvips \
      imagemagick && \
    rm -rf /var/lib/apt/lists/*

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3000
CMD ["bash", "-c", "bin/rails db:prepare && bin/rails server -b 0.0.0.0 -p 3000"]